biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js
biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-list.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-table-view.js
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tag-filter-view.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tag-filter-view.js

The Search results should use data tables while following 508 compliance. 
Makes the white space around the +/- buttons not clickable
Makes the white space outside the tags not clickable

ALS-3042, ALS-2761: New search results use datatables

---

biodatacatalyst-ui/src/main/webapp/picsureui/common/mainLayout.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/openMainLayout.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/outputPanel.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesPanel.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/query-results-view.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-list.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/selection-panel.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/selection-search-panel.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tool-suite-view.hbs

ALS-3561 AC
- On the search page, the results panel will be highlighted by being outlined in a box. We can make it be a panel of panels with the title “Results Panel”
- 
- “Results Panel” text should be shown above the Data Summary box
- 
- This should be implemented in both the Open and Authorized Access pages.

ALS-3561: adds result panel styling

---

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/genomic-filter-view.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/genomic-filter-view.js
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/selection-search-panel.hbs

* The hacky paddings are due to not being able to put a tooltip directly on a disabled button, and the button itself not propagating mouse events to the parent span.

ALS-3771: Require users to select a gene on the genomic filter modal

---

access-dashboard-metadata/confirm_new_version_subject_ids.ipynb

If a new version of a study uses the same subject IDs as the previous version, use this notebook to ensure the IDs match

New notebook to validate the new version of a study

---

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js

When a user is using the authorized search functionality they can no longer click on the "genomic filter" button while a search is currently in progress.

Update search-view genomic filter btn

---

biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanel.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanelView.js
biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/bdcTerraLink.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/bdcTerraLinkView.js
biodatacatalyst-ui/src/main/webapp/picsureui/common/pic-sure-dialog-view.js
biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/overrides/header.js
biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js

The old "User Profile" modal has been removed and substituted with a new API view that includes all the data from the previous modal, along with additional details related to the BDC API.

Als 4319 api tab should open a new page

---

biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanel.hbs

Made it so icons can't be clicked on if they are inside of an `<a>` element. This ensures that the <a> event will fire and not the icon one. I moved the icons for buttons that had it aligned to the left of the text. Lastly, I removed the span around the github button. This fixed the blank href issue.

Fix hyperlink icons

---

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/footer.js

Instead of attaching the listener directly to links we attach it to the document. When a user clicks on a link in a modal it should now open the warning modal.

Modify approach to open modal for link to confirm redirect

---

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js

Updating getInvalidActiveFilters we now check if they at least 'Gene_with_variant' in their query scope. We do not restrict genomic filtering based on studies so we cannot verify if they are permitted to access a specific gene like we can with selected variables.

Update router getInvalidActiveFilters

---

biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanel.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/overrides/footer.hbs

Any element nested with in an <a> element is no longer clickable. This ensure that if a <a> is clicked it's on click function fires.

Fix links across BDC

---

biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesPanelView.js
biodatacatalyst-ui/src/main/webapp/picsureui/overrides/footer.js

In order to be 508 compliant we need to ensure we focus on the original event.target after the modal is closed.

Update redirectModal to be 508 compliant

---

biodatacatalyst-ui/httpd-vhosts-dev.conf
biodatacatalyst-ui/httpd-vhosts.conf

We require the addition of "blob" to the image content security policy, allowing us to download the statistical visualization image of graphs.

Add blob to CSP

---

biodatacatalyst-ui/httpd-vhosts-dev.conf
biodatacatalyst-ui/httpd-vhosts.conf
biodatacatalyst-ui/src/main/webapp/picsureui/common/mainLayout.hbs

[ALS-4797] add google analytics to core UI. Can now be set via Jenkins global environment variable named `analytics_id`.

[ALS-4797] add google analytics to core UI

---

biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanelView.js

Variable name was reused, causing the component to fail to render.

Fix API token render

---

biodatacatalyst-ui/Dockerfile

[ALS-5144] I have added clarifying documentation to the top of the Dockerfile. It explains how the IS_OPEN_ACCESS argument is used.

[ALS-5144] Add documentation to file

---

biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/overrides/header.js

[ALS-5439] Add Open Access header

[ALS-5439] Add Open Access header

---

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js

[ALS-2794] Avoid using FHS for Auth Access Product Walkthrough. We now use "cardiac surgery" for all users.

[ALS-2794] Avoid using FHS for Auth Access Product Walkthrough

---

biodatacatalyst-ui/src/main/webapp/picsureui/landing/landing.js

[ALS-5534]  The order of operations has been altered in the landing.js file of the BioDataCatalyst UI. The current changes involve rendering the template right after the function is invoked rather than waiting until the end. This reordering will allow the loading icons to display until all ajax request are complete.

[ALS-5534] Render template earlier in landing.js

---

biodatacatalyst-ui/src/main/webapp/picsureui/common/pic-dropdown.js

No longer toggles the wrong dropdown menu if two menus are present in the header. Now calculates if the dropdown menu would go beyond the viewport's width. If it does, it recalculates the left property to align the dropdown to the right edge of the screen. Lastly, the dropdown is now focused appropriately.

[ALS-5703] AIM-AHEAD PIC-SURE Help Tab

---

biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModal.js
biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js

The code has been refactored to unify the selection process of search terms in search view. Regardless of open or authorized access, the search term used will now be determined by the `tourSearchTerm` option provided. Default term for open access is "epilepsy" while for authorized access it can vary, for instance, "cardiac surgery" in biodatacatalyst and "race" in aim-ahead.

[ALS-6058] Refactor search term selection in search view

---

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js

[ALS-5548] When building the data map we first filter out stigmatized variables so they are not displayed in the data-table.

[ALS-5548] Stigmatizing Variables Displayed in Dataset View of Open PIC-SURE

---

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-model.js

Added conditions in filter-model.js to only include the Parent Study Accession and TOPMed Study Accession with Subject ID filters if 'include_bdc_specific_filters' is true or undefined in settings.

"Conditionally add BioData Catalyst-specific filters"

---

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.hbs
biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js

Loading `plotly.js` now uses a promise to await the response before we begin to render the actual graphs.

[ALS-6223] Duplicate graphs on BDC StatViz
