hms-dbmi/pic-sure-bdc-frontend

biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccessFunctions.js, biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccessTemplate.hbs
https://hms-dbmi.atlassian.net/browse/ALS-1355
=> Do not display "Request" for studies with "c0" consent code

biodatacatalyst-ui/src/main/webapp/picsureui/output/outputPanel.hbs
https://hms-dbmi.atlassian.net/browse/ALS-1031
=> Remove the "Select Data" button and treeview from the outputPanel.hbs

biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.hbs
https://hms-dbmi.atlassian.net/browse/ALS-1640
=> Change label from "Genomic Samples" to "Samples Sequenced"

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js, biodatacatalyst-ui/src/main/webapp/psamaui/login/fence_login.hbs
Corresponds to the work in this PR: https://github.com/hms-dbmi/pic-sure-hpds-ui/pull/31
=> ALS-1464: Set BDC default action to the data access page

biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/outputPanel.js
https://hms-dbmi.atlassian.net/browse/ALS-1923
=> Fixes open PIC-SURE, consent code should not display "(withdrawn)"

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/outputPanel.js
https://hms-dbmi.atlassian.net/browse/ALS-1924
=> Changes display method of Select button to use .css("display", "block")

biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/README.md
https://hms-dbmi.atlassian.net/browse/ALS-1768
=> ALS-1768: Update README for Study Access code

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/selection-search-panel-view.js
Genomic filter modal wouldn't open after switching between open and authorized access
=> Fixes genomic filter modal bug

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js, biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css, biodatacatalyst-ui/src/main/webapp/picsureui/picSure/queryBuilder.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-list-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-model.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/no-results-help-view.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/no-results-help-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/no-results-partial.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/query-results-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-list.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tag-filter-model.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tag-filter-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
ALS-3316: Harmonized study tag should be listed first (regardless if it has less results) 
ALS-3317: Open Access and Authorized Access search results views are flashing on each other's views
ALS-2974: See some stigmatizing variable information in Open Access
=> ALS-3316, ALS-2974, and 3317

biodatacatalyst-ui/src/main/webapp/picsureui/common/pic-dropdown.js, biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-list-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tool-suite-help-view.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tool-suite-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
ALS-3347 - Disable tool suite for 0 participants
=> ALS-3347 & ALS-3362: New Navigation

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-list-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-model.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/no-results-help-view.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-util.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/studies-data-cache.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-template.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Included in this PR:
- ALS-3340: Search result Data retrieval export checkbox behavior
- ALS-3305: When a DCC Harmonized filter is applied and a user selects a non-DCC Harmonized variable from a non-compliant study for export the user is sent to Unauthorized page.
- ALS-3306: When a user filters on a non-Harmonized variable and adds a harmonized variable to export, the export is empty.
=> ALS-3340, ALS-3305, ALS-3306

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js, biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.hbs, biodatacatalyst-ui/src/main/webapp/psamaui/login/fence_login.hbs
Updates results panel and removes invalid filters when navigating to authorized access
=> ALS-3652 & ALS-3656

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/pic-image-modal-view.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/pic-image-modal-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
- Hides Guide Me btn when switching between pages
- Adds image count to bottom of guide modal
- Fixes bug ALS-3724
=> ALS-3718: Guide me fixes

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/package-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.js
-Added consent indicators to accession column in data access table
-Changed the horizontal scroll for the data access table to be connected to window horizontal scroll
-Removed the button for 7 bridges export when there was a data overload
=> Three small tickets

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/terra-export-view.hbs
=> Change links in export to terra modal

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/terra-export-view.hbs
=> Al s 4372 update buttons in terra export modal

biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/bdcTerraLink.hbs
Add new button to "BDC Powered by Terra" modal.
=> Add new "R - RStudio" button

biodatacatalyst-ui/httpd-vhosts-dev.conf, biodatacatalyst-ui/httpd-vhosts.conf, biodatacatalyst-ui/src/main/webapp/picsureui/overrides/header.js
Include CSP and X-Frame-Options headers to prevent clickjacking.
=> Als 4267 bdc security findings click jacking

biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/searchHelpTooltipOpen.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/query-results-help-view.hbs
Merging master into genomic-filter-rework before deployment
=> Merging master into genomic-filter-rework

biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/outputPanel.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tool-suite-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
We can remove this code because the other category is now handled correctly.
=> [ALS-4943] Remove temp "other" category Stat Vis fix

biodatacatalyst-ui/src/main/resources/bannerConfig.json, biodatacatalyst-ui/src/main/resources/banner_config.json
This banner section can be configured by updating the bannerConfig.json.
=> [ALS-5107] Add configurable banner section

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
[ALS-5105][ALS5106] Alter to use BDC blue for dataset
=> [ALS-5105][ALS5106] Alter to use bdc blue for dataset

biodatacatalyst-ui/src/main/webapp/picsureui/overrides/dataset/dataset-view.js
Requires [pic-sure-core-frontend #170](https://github.com/hms-dbmi/pic-sure-core-frontend/pull/170).
=> [ALS-4773] Update to dataset view overrides

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
[ALS-5186] Add legend to Stat Vis for Obfuscated region
[ALS-4957] BDC StatViz: Continuous bar should show true number when participants have only one value.
=> [ALS-5186] Add legend to Stat Vis for Obfuscated region

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.hbs, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
[ALS-5186] Update visualization wording
=> [ALS-5186] Update visualization wording

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
[ALS-5229] decode session value for search
=> [ALS-5229] Incorporate-icons-and-search-bar-on-Open-PIC-SURE-landing-page

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
[ALS-5456] This update revises the visualization-modal-view.js file by transferring Plotly from the primary module dependencies to a newly introduced loadPlotly method. This strategy enables lazy loading of the Plotly library.
=> [ALS-5456] Implement lazy load for Plotly in visualization-modal-view

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js, biodatacatalyst-ui/src/main/webapp/psamaui/login/not_authorized.hbs
[ALS-5567] Replaced the hard-coded URLs in not_authorized.hbs with dynamic, template-style variables. Now, the help link and login link URLs would not have to be changed directly in the file, reducing chances for bugs or errors.
=> [ALS-5567] Replace hard-coded URLs with variables in not_authorized.hbs

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-util.js
[ALS-5760] Add ternary operator to handle null case
=> [ALS-5760] Add ternary operator to handle null case

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
Added a dependency on ontology instance to the search-view module. The module now waits for all ontology info columns to load before rendering. This ensures that the variable "hasGenomicData" is properly initialized, improving data consistency and accuracy.
=> [ALS-5584] Add ontology instance dependency to search-view

biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModal.js
[ALS-5077] BDC: Obfuscation in Participant Counts by Study
=> [ALS-5077] BDC: Obfuscation in Participant Counts by Study

biodatacatalyst-ui/src/main/webapp/picsureui/landing/landing.js, biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModal.js, biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js, biodatacatalyst-ui/src/main/webapp/picsureui/overrides/search.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-list-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/package-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
[ALS-5082] Persist database: Flyway
=> [ALS-5082] Persist database: Flyway

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js
Update condition for variable display in datatable-filter-modal-view
=> Update condition for variable display in datatable-filter-modal-view

biodatacatalyst-ui/Dockerfile, biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-model.js
[ALS-6165] Disable directory browsing
=> [ALS-6165] Disable directory browsing 

biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js
[ALS-6308] Updated tooltip message for disabled filter variables
=> [ALS-6308] Updated tooltip message for disabled filter variables
